# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ohci_pci" "ehci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" "snd-aloop" ];
  boot.kernelParams = [ "snd-aloop.index=10" "threadirqs" ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
    "dev.hpet.max-user-freq" = 3072;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1541a90c-fd26-496c-9e53-033abf751b7c";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3b3f7ef4-55bf-4e73-a80d-0b2ec17c88a8";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/d08362aa-1d99-4e73-8fcb-f5a931ddf8c9";
      fsType = "ext2";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/D0A3-51DC";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fe31e3c0-e5d7-48b1-8446-716eb8a459c1"; }
    ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
